#!/bin/bash

#Rotate and zealous crop PNGs generated by jonathan's script ps2png.prl
#This script requires the imagemagick package

#Rotate only if width is less than height

echo rotating...

mogrify -rotate "90<" *.png

#Remove whitespace margins from image

echo trimming...

mogrify -trim +repage *.png

echo done
